# Generated by Django 5.2.1 on 2025-08-04 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('court', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='casequerylog',
            old_name='created_at',
            new_name='queried_at',
        ),
        migrations.AlterField(
            model_name='casequerylog',
            name='case_type',
            field=models.CharField(max_length=20),
        ),
    ]
